/* Generated By:JJTree: Do not edit this line. ASTArrayFirst.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=interpreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.ast;

public
class ASTArrayFirst extends SimpleNode {
  public ASTArrayFirst(int id) {
    super(id);
  }

  public ASTArrayFirst(Simp p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=edcf10b69818b8b5ef2fa367b16e1c36 (do not edit this line) */
