/* Generated By:JJTree: Do not edit this line. ASTArrayRemove.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=interpreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.ast;

public
class ASTArrayRemove extends SimpleNode {
  public ASTArrayRemove(int id) {
    super(id);
  }

  public ASTArrayRemove(Simp p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5de43dc5186a5a93a729eabe5452a0d0 (do not edit this line) */
