/* Generated By:JJTree: Do not edit this line. ASTAdditionAssignment.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=interpreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.ast;

public
class ASTAdditionAssignment extends SimpleNode {
  public ASTAdditionAssignment(int id) {
    super(id);
  }

  public ASTAdditionAssignment(Simp p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d271dfb7e84f7143a6ac451c372ecac3 (do not edit this line) */
