/* Generated By:JJTree: Do not edit this line. ASTArrayGetIndex.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=interpreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.ast;

public
class ASTArrayGetIndex extends SimpleNode {
  public ASTArrayGetIndex(int id) {
    super(id);
  }

  public ASTArrayGetIndex(Simp p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e2831558ba01bc00dba28f6d630fd1a9 (do not edit this line) */
