/* Generated By:JJTree: Do not edit this line. ASTDictionaryList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=interpreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.ast;

public
class ASTDictionaryList extends SimpleNode {
  public ASTDictionaryList(int id) {
    super(id);
  }

  public ASTDictionaryList(Simp p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9655edfb68eedc1b346bae149b9267e6 (do not edit this line) */
