/* Generated By:JJTree: Do not edit this line. ASTPrintLn.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=interpreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.ast;

public
class ASTPrintLn extends SimpleNode {
  public ASTPrintLn(int id) {
    super(id);
  }

  public ASTPrintLn(Simp p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ef93c88d894f74fdd7aa3c080a2aafd6 (do not edit this line) */
