/* Generated By:JavaCC: Do not edit this line. SiliTreeConstants.java Version 5.0 */
package parser.ast;

public interface SiliTreeConstants
{
  public int JJTCODE = 0;
  public int JJTSTATEMENT = 1;
  public int JJTBLOCK = 2;
  public int JJTPARMLIST = 3;
  public int JJTFNBODY = 4;
  public int JJTFNDEF = 5;
  public int JJTRETURNEXPRESSION = 6;
  public int JJTVOID = 7;
  public int JJTASSIGNMENT = 8;
  public int JJTADDITIONASSIGNMENT = 9;
  public int JJTSUBTRACTIONASSIGNMENT = 10;
  public int JJTARRAYSETINDEX = 11;
  public int JJTARRAYGETINDEX = 12;
  public int JJTARRAYPUSH = 13;
  public int JJTARRAYPOP = 14;
  public int JJTARRAYLENGTH = 15;
  public int JJTARRAYPRINT = 16;
  public int JJTARRAYFIRST = 17;
  public int JJTARRAYLAST = 18;
  public int JJTARRAYINSERT = 19;
  public int JJTARRAYREMOVE = 20;
  public int JJTDICTPUT = 21;
  public int JJTDICTGET = 22;
  public int JJTDICTPOP = 23;
  public int JJTDICTREPLACE = 24;
  public int JJTIFSTATEMENT = 25;
  public int JJTFORLOOP = 26;
  public int JJTWHILELOOP = 27;
  public int JJTFORTOLOOP = 28;
  public int JJTPRINT = 29;
  public int JJTPRINTLN = 30;
  public int JJTQUIT = 31;
  public int JJTCALL = 32;
  public int JJTARGLIST = 33;
  public int JJTOR = 34;
  public int JJTAND = 35;
  public int JJTCOMPEQUAL = 36;
  public int JJTCOMPNEQUAL = 37;
  public int JJTCOMPGTE = 38;
  public int JJTCOMPLTE = 39;
  public int JJTCOMPGT = 40;
  public int JJTCOMPLT = 41;
  public int JJTADD = 42;
  public int JJTSUBTRACT = 43;
  public int JJTTIMES = 44;
  public int JJTDIVIDE = 45;
  public int JJTREMAINDER = 46;
  public int JJTPOW = 47;
  public int JJTSQRT = 48;
  public int JJTRANDOM = 49;
  public int JJTFLOOR = 50;
  public int JJTCOS = 51;
  public int JJTSIN = 52;
  public int JJTUNARYNOT = 53;
  public int JJTUNARYPLUS = 54;
  public int JJTUNARYMINUS = 55;
  public int JJTARRAYLIST = 56;
  public int JJTDICTIONARYLIST = 57;
  public int JJTFNINVOKE = 58;
  public int JJTIDENTIFIER = 59;
  public int JJTDEREFERENCE = 60;
  public int JJTCHARACTER = 61;
  public int JJTINTEGER = 62;
  public int JJTRATIONAL = 63;
  public int JJTTRUE = 64;
  public int JJTFALSE = 65;


  public String[] jjtNodeName = {
    "Code",
    "Statement",
    "Block",
    "Parmlist",
    "FnBody",
    "FnDef",
    "ReturnExpression",
    "void",
    "Assignment",
    "AdditionAssignment",
    "SubtractionAssignment",
    "ArraySetIndex",
    "ArrayGetIndex",
    "ArrayPush",
    "ArrayPop",
    "ArrayLength",
    "ArrayPrint",
    "ArrayFirst",
    "ArrayLast",
    "ArrayInsert",
    "ArrayRemove",
    "DictPut",
    "DictGet",
    "DictPop",
    "DictReplace",
    "IfStatement",
    "ForLoop",
    "WhileLoop",
    "ForToLoop",
    "Print",
    "PrintLn",
    "Quit",
    "Call",
    "ArgList",
    "Or",
    "And",
    "CompEqual",
    "CompNequal",
    "CompGTE",
    "CompLTE",
    "CompGT",
    "CompLT",
    "Add",
    "Subtract",
    "Times",
    "Divide",
    "Remainder",
    "Pow",
    "Sqrt",
    "Random",
    "Floor",
    "Cos",
    "Sin",
    "UnaryNot",
    "UnaryPlus",
    "UnaryMinus",
    "ArrayList",
    "DictionaryList",
    "FnInvoke",
    "Identifier",
    "Dereference",
    "Character",
    "Integer",
    "Rational",
    "True",
    "False",
  };
}
/* JavaCC - OriginalChecksum=586dfa2e96b2f473bb27ceea5fd66820 (do not edit this line) */
