/* Generated By:JJTree&JavaCC: Do not edit this line. SimpConstants.java */
package parser.ast;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 7;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int ELSE = 10;
  /** RegularExpression Id. */
  int FOR = 11;
  /** RegularExpression Id. */
  int FORT = 12;
  /** RegularExpression Id. */
  int TO = 13;
  /** RegularExpression Id. */
  int STEP = 14;
  /** RegularExpression Id. */
  int WHILE = 15;
  /** RegularExpression Id. */
  int PRINT = 16;
  /** RegularExpression Id. */
  int PRINTLN = 17;
  /** RegularExpression Id. */
  int QUIT = 18;
  /** RegularExpression Id. */
  int FUNCTION = 19;
  /** RegularExpression Id. */
  int RETURN = 20;
  /** RegularExpression Id. */
  int OR = 21;
  /** RegularExpression Id. */
  int AND = 22;
  /** RegularExpression Id. */
  int NOT = 23;
  /** RegularExpression Id. */
  int TRUE = 24;
  /** RegularExpression Id. */
  int FALSE = 25;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 26;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 27;
  /** RegularExpression Id. */
  int HEX_LITERAL = 28;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 29;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 30;
  /** RegularExpression Id. */
  int EXPONENT = 31;
  /** RegularExpression Id. */
  int STRING_LITERAL = 32;
  /** RegularExpression Id. */
  int IDENTIFIER = 33;
  /** RegularExpression Id. */
  int LETTER = 34;
  /** RegularExpression Id. */
  int DIGIT = 35;
  /** RegularExpression Id. */
  int LPAREN = 36;
  /** RegularExpression Id. */
  int RPAREN = 37;
  /** RegularExpression Id. */
  int LBRACE = 38;
  /** RegularExpression Id. */
  int RBRACE = 39;
  /** RegularExpression Id. */
  int LBRACKET = 40;
  /** RegularExpression Id. */
  int RBRACKET = 41;
  /** RegularExpression Id. */
  int SEMICOLON = 42;
  /** RegularExpression Id. */
  int COMMA = 43;
  /** RegularExpression Id. */
  int DOT = 44;
  /** RegularExpression Id. */
  int PP = 45;
  /** RegularExpression Id. */
  int MM = 46;
  /** RegularExpression Id. */
  int ASSIGN = 47;
  /** RegularExpression Id. */
  int PEQ = 48;
  /** RegularExpression Id. */
  int MEQ = 49;
  /** RegularExpression Id. */
  int UEQ = 50;
  /** RegularExpression Id. */
  int EQ = 51;
  /** RegularExpression Id. */
  int GT = 52;
  /** RegularExpression Id. */
  int LT = 53;
  /** RegularExpression Id. */
  int LE = 54;
  /** RegularExpression Id. */
  int GE = 55;
  /** RegularExpression Id. */
  int NE = 56;
  /** RegularExpression Id. */
  int HOOK = 57;
  /** RegularExpression Id. */
  int COLON = 58;
  /** RegularExpression Id. */
  int PLUS = 59;
  /** RegularExpression Id. */
  int SUBT = 60;
  /** RegularExpression Id. */
  int STAR = 61;
  /** RegularExpression Id. */
  int SLASH = 62;
  /** RegularExpression Id. */
  int REM = 63;
  /** RegularExpression Id. */
  int POW = 64;
  /** RegularExpression Id. */
  int SQRT = 65;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"IF\"",
    "\"ELSE\"",
    "\"FOR\"",
    "\"FORT\"",
    "\"TO\"",
    "\"STEP\"",
    "\"WHILE\"",
    "\"PRINT\"",
    "\"PRINTLN\"",
    "\"QUIT\"",
    "\"FUNCTION\"",
    "\"RETURN\"",
    "\"OR\"",
    "\"AND\"",
    "\"NOT\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"++\"",
    "\"--\"",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"@=\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"?\"",
    "\":\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"**\"",
    "\".getIndex\"",
    "\".setIndex\"",
    "\".push\"",
    "\".pop\"",
    "\".length\"",
    "\".print\"",
    "\".first\"",
    "\".last\"",
    "\".insert\"",
    "\".remove\"",
    "\".put\"",
    "\".get\"",
    "\".replace\"",
    "\"<>\"",
    "\"~\"",
    "\"@\"",
    "\"@@\"",
  };

}
